/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 21-Feb-2023 14:40:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 244
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 244;
const int16_t demoFilter[244] = {
        4,      2,      2,      3,      3,      4,      4,      5,      6,
        7,      7,      8,      9,     10,     11,     12,     13,     14,
       15,     16,     16,     17,     18,     18,     19,     19,     19,
       19,     19,     18,     18,     17,     15,     14,     12,     10,
        7,      4,      1,     -2,     -6,    -11,    -15,    -20,    -26,
      -32,    -38,    -44,    -51,    -57,    -64,    -72,    -79,    -86,
      -94,   -101,   -109,   -116,   -123,   -130,   -136,   -142,   -148,
     -153,   -157,   -161,   -164,   -166,   -167,   -167,   -166,   -164,
     -160,   -156,   -150,   -143,   -134,   -125,   -113,   -100,    -86,
      -70,    -53,    -34,    -14,      7,     30,     54,     79,    106,
      133,    162,    191,    222,    253,    284,    317,    349,    382,
      414,    447,    479,    511,    543,    574,    604,    633,    661,
      688,    714,    738,    761,    782,    801,    818,    834,    847,
      858,    867,    874,    879,    881,    881,    879,    874,    867,
      858,    847,    834,    818,    801,    782,    761,    738,    714,
      688,    661,    633,    604,    574,    543,    511,    479,    447,
      414,    382,    349,    317,    284,    253,    222,    191,    162,
      133,    106,     79,     54,     30,      7,    -14,    -34,    -53,
      -70,    -86,   -100,   -113,   -125,   -134,   -143,   -150,   -156,
     -160,   -164,   -166,   -167,   -167,   -166,   -164,   -161,   -157,
     -153,   -148,   -142,   -136,   -130,   -123,   -116,   -109,   -101,
      -94,    -86,    -79,    -72,    -64,    -57,    -51,    -44,    -38,
      -32,    -26,    -20,    -15,    -11,     -6,     -2,      1,      4,
        7,     10,     12,     14,     15,     17,     18,     18,     19,
       19,     19,     19,     19,     18,     18,     17,     16,     16,
       15,     14,     13,     12,     11,     10,      9,      8,      7,
        7,      6,      5,      4,      4,      3,      3,      2,      2,
        4
};
