/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 21-Feb-2023 15:43:31
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 68
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */

const int16_t demoFilter[] = {
        0,      2,      3,      5,      9,     15,     23,     33,     47,
       65,     87,    114,    146,    184,    227,    277,    334,    396,
      463,    536,    612,    692,    774,    857,    939,   1019,   1095,
     1165,   1229,   1285,   1331,   1366,   1390,   1403,   1403,   1390,
     1366,   1331,   1285,   1229,   1165,   1095,   1019,    939,    857,
      774,    692,    612,    536,    463,    396,    334,    277,    227,
      184,    146,    114,     87,     65,     47,     33,     23,     15,
        9,      5,      3,      2,      0
};
