/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 10-Mar-2023 17:42:34
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 70
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
//const int BL = 70;
const int16_t demoFilter[70] = {
        6,      8,     12,     18,     25,     34,     46,     59,     76,
       95,    118,    143,    172,    205,    240,    279,    320,    365,
      412,    460,    511,    562,    614,    665,    715,    764,    810,
      854,    893,    928,    958,    983,   1002,   1015,   1022,   1022,
     1015,   1002,    983,    958,    928,    893,    854,    810,    764,
      715,    665,    614,    562,    511,    460,    412,    365,    320,
      279,    240,    205,    172,    143,    118,     95,     76,     59,
       46,     34,     25,     18,     12,      8,      6
};
